version: '3.8'
services:
  devcontainer:
    image: devcontainer-ml/devcontainer-ml
    build:
      context: .
      dockerfile: ./dev.Dockerfile
    volumes:
      - ../..:/workspaces:cached
    # network_mode: service:db
    command: sleep infinity
    # Pytorch / cuda configuration options
    ipc: host
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
      memlock:
        soft: -1
        hard: -1
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
  # db:
  #   image: postgres:latest
  #   restart: unless-stopped
  #   volumes:
  #     - postgres-data:/var/lib/postgresql/data
  #   environment:
  #     POSTGRES_PASSWORD: postgres
  #     POSTGRES_USER: postgres
  #     POSTGRES_DB: postgres

# volumes:
#   postgres-data:
