services:
  database:
    image: 'pgvector/pgvector:pg16'
    ports:
      - 15432:5432
    expose:
      - 5432
    env_file:
      - .env
    volumes:
      - ./pg_init.d:/docker-entrypoint-initdb.d
      - pgdata:/var/lib/postgresql/data/
  
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 15433:80
    env_file:
      - .env
    depends_on:
      - database
    volumes:
      - pgadmin-data:/var/lib/pgadmin/
  
  mlflow:
    image: mlflow/mlflow-psycopg2
    build: 
      context: .
      dockerfile: mlflow.Dockerfile
    command: mlflow server --host 0.0.0.0 --port 5021 --backend-store-uri "postgresql+psycopg2://postgres:postgres@database:5432/vector_db" 
    ports: 
      - 5021:5021
    volumes:
      - mlruns:/mlruns
      - artifacts:/root/artifacts


volumes:
  pgadmin-data:
  pgdata:
  mlruns:
  artifacts: